### ISSUE TITLE
DPI scale issue on multiple monitors

### ISSUE THREAD

**Issue by Mythique** [Wassimulator/CactusViewer#11]
With two monitors the UI is blurry.

Current setup:
- Screen 1, 100% scale: UI is fine.
- Screen 2, 125% scale: UI is blurry. The window scale to the proper size when dragging the window there.

The window should still scale properly, but the UI shouldn't be blurry.

If I understand it correctly, the app needs to be ["DPI aware"](https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows).

**Comment by Wassimulator** [comment]
fixed :)

**Comment by Wassimulator** [comment]
fixed :)

**Comment by Mythique** [comment]
Hello,

It fixed the blurriness, unfortunately the UI and window do not seem to be scaled properly.

If I drag the same program from a screen with and 100% scale to another 125%, the UI and text should get bigger respecting this scale, without it getting blurry of course.

Meanwhile CactusViewer is staying at a fixed scale when dragging the window, it does not seem to take the scale into account.

With that said, your fix is still an improvement from the previous version.

**Comment by Mythique** [comment]
I wanted to look a bit at this issue for my personal knowledge (unfortunately I don't know enough C++ and win32 to help improve this).

As far as I understand, Cactus is not using the _new_ way to handle DPI scaling. Playing with [the program from the Windows-classic-samples](https://github.com/Microsoft/Windows-classic-samples/tree/main/Samples/DPIAwarenessPerWindow) I notice it has a similar behaviour to Windows 8.1 (any windows 10 ways seems to be fine ?) :
![image](https://github.com/Wassimulator/CactusViewer/assets/4488088/ee8b3d3e-4592-4c32-9add-c4b03cfcac0f)

The issue with this are :
- The title bar is not scaled properly
- Any system dialog will not be scaled properly
- The window is not resized when moving to another monitor
