### ISSUE TITLE
App fails to startup when CWD is not bin/

### ISSUE THREAD

**Issue by StevenSavold** [Wassimulator/CactusViewer#23]
When starting the app while your current working directory is not the bin/ folder, the app crashes. It seems the app fails to load the default font. It would be great to embed the font file in the exe when building to prevent this.

**Comment by Wassimulator** [comment]
Are you running a debug build? This is expected in a debug build, release should work from anywhere

**Comment by StevenSavold** [comment]
You are right, I was running a debug build. I'm sorry, and thank you :)
