### ISSUE TITLE
Crash opening file from command line or `Open with...`

### ISSUE THREAD

**Issue by azmr** [Wassimulator/CactusViewer#25]
CactusViewer crashes when started in a way that will immediately open an image.

The crash appears to be in `atidxx64.dll`

Some observations:
- Opening method
  - error when opening from command-line: `C:\bin\CactusViewer.exe "D:\Photos\2023 Seattle\phillip_avatar.png"`
  - error when opening with `file explorer > right click image > Open with`
  - no error when starting CactusViewer then using `Open` dialogue
- Format
  - error for both JPG & PNG
- Path
  - error for paths on different drives & with/without spaces: `C:\Photos\phillip_avatar.png` & `"D:\Photos\2023 Seattle\phillip_avatar.png"`
- Occurs completely consistently (no obvious randomness)

Caveat:
- It's possible there's something wrong with my graphics drivers, as I have had problems with other software. (Windows photo viewer currently works fine though)

**Comment by tek256** [comment]
Able to reproduce by running:
```
.\CactusViewer.exe OfficeFloorplan.png
```

![image](https://github.com/Wassimulator/CactusViewer/assets/3059752/72757010-e440-462c-a6d4-794aab6038b3)

**Comment by azmr** [comment]
Interestingly this isn't quite the same as the crash I'm seeing.
Mine is a read access violation from at `0x0008`

I got the same assert hit as this when trying `CactusViewer.exe --help`
(and similar), but Wassim said that just wasn't handled yet.

**Comment by Wassimulator** [comment]
should be fixed with #35 
Please report any issues if there are any missed edgecases!
yeah I need to support --help at some point indeed, but there isn't much to do in the cmdline but open a file.
