### ISSUE TITLE
Why there is no thumbnail support?

### ISSUE THREAD

**Issue by AndrejusAnto** [Wassimulator/CactusViewer#32]
Just wondering why there is no support for image thumbnail?

**Comment by Wassimulator** [comment]
What do you mean exactly? ICO files or are thumbnails not showing up in
explorer for you?

**Comment by AndrejusAnto** [comment]
On windows (explorer and desktop))  image files shows cactusviewer icon (i think) not a thumbnail as other apps i used and because cactusviewer  is just exe file, not installable like nomacs, so was wondering maybe there is a reason why it is not working/supported.

**Comment by Wassimulator** [comment]
I see what you mean. For me I had to manually set the default viewer for each file I open, it now shows thumbs for each file. It's not an issue on the programming of the program but rather on windows as you have gathered. I need to make an installer of sorts to set defaults.

**Comment by Wassimulator** [comment]
I just added an installer, let me know if this addresses the issue.

**Comment by AndrejusAnto** [comment]
I'm sorry, I am stupid. When I removed your viewer with windows default viewer thumbnails still not working. Turns out it was windows feature that was turn off. Sorry for bothering and thanks for handmade style app.

**Comment by Wassimulator** [comment]
No worries! Glad it was resolved for you one way or another. :)
