### ISSUE TITLE
CactusViewer is now in Scoop bucket "extras" - Update readme with install instructions?

### ISSUE THREAD

**Issue by o-l-a-v** [Wassimulator/CactusViewer#34]
CactusViewer is now in Scoop bucket "Extras":

* <https://github.com/ScoopInstaller/Extras/blob/master/bucket/cactusviewer.json>

It can be installed by:

1. Install Scoop, if you don't have it already.
   * <https://scoop.sh/> 
   ```pwsh
   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
   Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
   ```
2. Add the Extras bucket, if you don't have it already.
   * `scoop bucket add extras` 
3. Install CactusViewer with Scoop.
   * `scoop install extras/cactusviewer`

It will add a shortcut to the start menu, and CactusViewer is also added to PATH so it can be ran from CMD without specifying the full path.

---

Would you like a PR with install instructions to README, or do you want to add it yourself? 🙂

**Comment by Wassimulator** [comment]
Awesome! 
Yes please, feel free to PR, I'll merge it directly. sorry for the late reply! I missed the notification for this issue
