### ISSUE TITLE
CactusViewer failing to get system font path

### ISSUE THREAD

**Issue by ghost** [Wassimulator/CactusViewer#36]
I am on commit b30990314943830f11b2d3dfc45ce69c2449d174

CactusViewer is crashing on startup in UI_load_font_file because get_font_file_from_system is outputting an invalid font path:

![image](https://github.com/Wassimulator/CactusViewer/assets/91440203/87dbcd85-7666-44f6-98ec-c11ea7be6d58)

https://github.com/Wassimulator/CactusViewer/blob/b30990314943830f11b2d3dfc45ce69c2449d174/src/source.cpp#L599-L603

It looks like RegQueryValueExA is succeeding but outputting an empty string (value = "", value_length = 1). Looking at [the MSDN page for RegQueryValueExA ](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryvalueexa#examples) this seems to be a correct use of the function so I'm not sure what's going on.

**Comment by Wassimulator** [comment]
I was worried it will fail _somewhere_ .. I'll look into it soon. It works on my end.

**Comment by Wassimulator** [comment]
@hkva  could you try it now? I changed the way I get the font path, there might be some weird indirection going on here in registry files.

**Comment by ghost** [comment]
Tried it again on a741e72704b7bacdc0efea43500a44760f0a1298, system_font is still "C:\\Windows\\Fonts\\"

**Comment by Wassimulator** [comment]
what Windows version do you have? what font IS available on your system? if you're stepping through the function is `value` empty?
