### ISSUE TITLE
Reloading directory while deleted file is in view causes assertion fail.

### ISSUE THREAD

**Issue by mauskin** [Wassimulator/CactusViewer#6]
If the file being views in CactusViewer is deleted and then you click Reload folder the assertion failure message is shown.

Version 1.2.3 - 03/2023

![Screenshot 2023-05-10 at 15 36 56](https://github.com/Wassimulator/CactusViewer/assets/5677012/90270e3e-8d48-4dd4-a141-724b5addf988)

**Comment by Wassimulator** [comment]
Thanks for reporting, fixed this, now when the file is deleted and the folder is reloaded the viewer switches to the first file in the folder.
